export const articlesData = {
  ciencia: [
    {
      id: 1,
      title: "Inteligencia Artificial en la Medicina Moderna",
      summary:
        "Exploramos cómo la IA está revolucionando el diagnóstico médico y mejorando la atención al paciente en hospitales de todo el mundo.",
      author: "Dr. María González",
      date: "2024-01-15",
      tag: "Artículo académico",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 2,
      title: "Energías Renovables: El Futuro Sostenible",
      summary: "Un análisis completo sobre las tecnologías de energía limpia y su impacto en el medio ambiente.",
      author: "Ing. Carlos Ruiz",
      date: "2024-01-10",
      tag: "Artículo de difusión",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 3,
      title: "Biotecnología y Agricultura del Siglo XXI",
      summary:
        "Cómo la biotecnología está transformando la producción de alimentos para alimentar a una población creciente.",
      author: "Dra. Ana Martínez",
      date: "2024-01-05",
      tag: "Artículo académico",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 4,
      title: "Robótica Avanzada en la Industria",
      summary: "El impacto de los robots inteligentes en la automatización industrial moderna.",
      author: "Ing. Pedro López",
      date: "2024-01-20",
      tag: "Artículo de difusión",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 5,
      title: "Computación Cuántica: El Próximo Salto",
      summary: "Explorando las posibilidades y desafíos de la computación cuántica.",
      author: "Dr. Laura Sánchez",
      date: "2024-01-18",
      tag: "Artículo académico",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 16,
      title: "Nanotecnología en la Medicina",
      summary: "Aplicaciones revolucionarias de la nanotecnología en tratamientos médicos.",
      author: "Dra. Carmen Vega",
      date: "2024-01-22",
      tag: "Artículo académico",
      image: "/placeholder.svg?height=200&width=300",
    },
  ],
  humanidades: [
    {
      id: 6,
      title: "La Literatura Latinoamericana Contemporánea",
      summary:
        "Un recorrido por las voces más importantes de la literatura actual en América Latina y su impacto cultural.",
      author: "Prof. Luis Hernández",
      date: "2024-01-12",
      tag: "Arte",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 7,
      title: "Filosofía y Tecnología: Un Diálogo Necesario",
      summary: "Reflexiones sobre el impacto filosófico de la tecnología en la sociedad moderna.",
      author: "Dr. Elena Vásquez",
      date: "2024-01-08",
      tag: "Artículo de difusión",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 8,
      title: "El Susurro del Tiempo",
      summary: "Un relato corto que explora la nostalgia y el paso del tiempo a través de los ojos de un anciano.",
      author: "Sofía Ramírez",
      date: "2024-01-03",
      tag: "Relato corto",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 9,
      title: "Arte Digital: Nueva Expresión Creativa",
      summary: "Cómo las herramientas digitales están redefiniendo el arte contemporáneo.",
      author: "Artista Maya Torres",
      date: "2024-01-17",
      tag: "Arte",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 17,
      title: "Historia del Arte Precolombino",
      summary: "Explorando las manifestaciones artísticas de las civilizaciones precolombinas.",
      author: "Dr. Roberto Méndez",
      date: "2024-01-21",
      tag: "Arte",
      image: "/placeholder.svg?height=200&width=300",
    },
  ],
  social: [
    {
      id: 10,
      title: "Participación Ciudadana en la Era Digital",
      summary:
        "Análisis sobre cómo las redes sociales están cambiando la forma en que los ciudadanos participan en la política.",
      author: "Lic. Roberto Silva",
      date: "2024-01-14",
      tag: "Nota social",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 11,
      title: "Desigualdad Social en América Latina",
      summary: "Un estudio sobre las causas y consecuencias de la desigualdad social en la región.",
      author: "Dra. Patricia López",
      date: "2024-01-09",
      tag: "Artículo académico",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 12,
      title: "Movimientos Juveniles Contemporáneos",
      summary: "El papel de los jóvenes en los cambios sociales actuales.",
      author: "Soc. Carmen Díaz",
      date: "2024-01-16",
      tag: "Nota social",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 18,
      title: "Impacto de la Migración en las Comunidades",
      summary: "Análisis sociológico sobre los efectos de la migración en las comunidades de origen y destino.",
      author: "Dr. Fernando Castro",
      date: "2024-01-23",
      tag: "Artículo académico",
      image: "/placeholder.svg?height=200&width=300",
    },
  ],
  logros: [
    {
      id: 13,
      title: "Estudiante de Ingeniería Gana Premio Nacional",
      summary: "Reconocimiento por proyecto innovador en energías renovables que beneficiará a comunidades rurales.",
      author: "Redacción J-UP",
      date: "2024-01-16",
      tag: "Logro",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 14,
      title: "Equipo de Debate Universitario Campeón Regional",
      summary: "Nuestro equipo de debate se corona campeón en el torneo regional de universidades del sureste.",
      author: "Redacción J-UP",
      date: "2024-01-11",
      tag: "Logro",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 15,
      title: "Investigación Médica Reconocida Internacionalmente",
      summary: "Estudio sobre enfermedades tropicales recibe reconocimiento de la OMS.",
      author: "Redacción J-UP",
      date: "2024-01-19",
      tag: "Logro",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 19,
      title: "Alumna Gana Beca de Excelencia Académica",
      summary: "Estudiante de psicología obtiene beca completa para estudios de posgrado en el extranjero.",
      author: "Redacción J-UP",
      date: "2024-01-24",
      tag: "Logro",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 20,
      title: "Proyecto de Sustentabilidad Premiado",
      summary: "Iniciativa estudiantil de reciclaje recibe reconocimiento nacional por su impacto ambiental.",
      author: "Redacción J-UP",
      date: "2024-01-25",
      tag: "Logro",
      image: "/placeholder.svg?height=200&width=300",
    },
  ],
}

